import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* Import Apex Mk2 from CDN */}
        <link href="https://fonts.cdnfonts.com/css/apex-mk2" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"rel="stylesheet"/>
      </head>
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
